name: Actions workflow

on:
  push:
  pull_request:
    types:
      - closed
      - assigned
      - opened
      - reopened

jobs:
  run-github-actions:
    runs-on: ubuntu-20.04
    steps:
      - name: List files
        run: |
          pwd
          ls
      - name: Checkout
        uses: actions/checkout@v1
      - name: List files agan
        run: |
          pwd
          ls -lpha
      - name: simple JS action
        id: simple-js
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Adam
      - name: Log greeting time
        run: echo "${{ steps.simple-js.outputs.time }}"