name: Actions workflow

on:
  pull_request:
    types:
      - closed
      - assigned
      - opened
      - reopened
#  push:
#    branches:
#      - master
#      - demo
#      - staging
#      - 'feature/*' # matches feature/yolo, and not feature/okay/no
#      - 'feature/**' # matches everything above
##    branches-ignore:
##      - yolo
#    tags:
#      - 'v1.*'
#    paths:
#      - '**.js' # any js file in our repo changes

jobs:
  run-github-actions:
    runs-on: ubuntu-20.04
    steps:
      - name: List files
        run: |
          pwd
          ls
      - name: Checkout
        uses: actions/checkout@v1
      - name: List files agan
        run: |
          pwd
          ls -lpha
      - name: simple JS action
        id: simple-js
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Adam
      - name: Log greeting time
        run: echo "${{ steps.simple-js.outputs.time }}"