name: Matrix
on: pull_request

jobs:
  node-version:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node_version: [6, 7, 8]
        include: # ez nem hozzáad egy újat, csak új változókat lehet hozzáadni bizonyos helyekre
          - os: ubuntu-latest
            node_version: 8
            is_ubuntu_8: igen
        exclude:
          - os: ubuntu-latest
            node_version: 6
      #fail-fast: true
      #max-parallel: 3
    steps:
      - name: Log node version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Log node version
        run: node -v