name: Shell Commands

on: [pull_request]

jobs:
  run-shell-command:
    runs-on: ubuntu-20.04
    steps:
      - name: echo a string
        run: echo "Hello yoolo"
      - name: multiline script
        run: |
          node -v
          npm -v